---
- name: Install Deno
  become: false
  shell: |
    set -e
    if ! command -v deno >/dev/null 2>&1; then
      curl -fsSL https://deno.land/install.sh | sh
    fi
  args:
    executable: /bin/bash

- name: Ensure Deno is on PATH in shells
  become: false
  lineinfile:
    path: "{{ item }}"
    create: yes
    line: 'export DENO_INSTALL="$HOME/.deno"; export PATH="$DENO_INSTALL/bin:$PATH"'
    state: present
  loop:
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.zshrc"
