---
- name: Install NVM
  become: false
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="{{ target_home }}/.nvm"
    if [ ! -d "$NVM_DIR" ]; then
      curl -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh" | bash
    fi
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ target_home }}"
    USER: "{{ target_user }}"

- name: Install Node LTS via NVM and set default
  become: false
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="{{ target_home }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
    nvm install "{{ node_lts }}"
    nvm alias default "{{ node_lts }}"
    nvm use default
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ target_home }}"

- name: Install pnpm globally via npm
  become: false
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="{{ target_home }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
    npm i -g pnpm
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ target_home }}"
