---
- name: Install Rust via rustup
  become: false
  ansible.builtin.shell: |
    set -e
    if ! command -v rustup >/dev/null 2>&1; then
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    fi
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ target_home }}"
    USER: "{{ target_user }}"

- name: Ensure cargo on PATH
  become: false
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: yes
    line: 'export PATH="{{ target_home }}/.cargo/bin:$PATH"'
    state: present
  loop:
    - "{{ target_home }}/.bashrc"
    - "{{ target_home }}/.zshrc"

- name: Update toolchains (idempotent)
  become: false
  ansible.builtin.shell: |
    set -e
    if command -v rustup >/dev/null 2>&1; then
      rustup toolchain install stable
      rustup default stable
      rustup update
    fi
  args:
    executable: /bin/bash
  changed_when: false
  environment:
    HOME: "{{ target_home }}"
