---
- name: Install Rust via rustup
  become: false
  shell: |
    set -e
    if ! command -v rustup >/dev/null 2>&1; then
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    fi
  args:
    executable: /bin/bash

- name: Ensure cargo on PATH
  become: false
  lineinfile:
    path: "{{ item }}"
    create: yes
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    state: present
  loop:
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.zshrc"

- name: Update toolchains (idempotent)
  become: false
  shell: |
    set -e
    if command -v rustup >/dev/null 2>&1; then
      rustup toolchain install stable
      rustup default stable
      rustup update
    fi
  args:
    executable: /bin/bash
  changed_when: false
