---
- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  become: yes

- name: Install oh-my-zsh (if not already installed)
  become: false
  ansible.builtin.shell: |
    set -e
    export ZSH="{{ target_home }}/.oh-my-zsh"
    if [ ! -d "$ZSH" ]; then
      RUNZSH=no KEEP_ZSHRC=yes \
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
  args:
    executable: /bin/bash
  changed_when: false
  environment:
    HOME: "{{ target_home }}"

- name: Set default shell to zsh for current user
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /usr/bin/zsh
  become: yes

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ target_home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master
    update: yes
  become: false
