---
# Base packages & utilities
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - build-essential
      - git
      - curl
      - unzip
      - htop
      - ripgrep
      - ca-certificates
      - tmux
      - python3
      - python3-pip
      - jq
      - fzf
    state: present

# tmux config is managed by yadm in ~/.config/tmux/tmux.conf

- name: Ensure TPM directory exists
  file:
    path: "{{ tpm_dir }}"
    state: directory
    mode: "0755"

- name: Clone TPM (tmux plugin manager)
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ tpm_dir }}"
    version: master
    update: yes

# Install tmux plugins (non-interactive)
- name: Install tmux plugins via TPM
  become: false
  shell: |
    tmux start-server
    tmux new-session -d 'bash' || true
    "{{ tpm_dir }}/bin/install_plugins"
    tmux kill-server || true
  args:
    executable: /bin/bash
  changed_when: false
