- name: Download Neovim 0.11.3 deb
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-linux64.deb
    dest: /tmp/nvim.deb

- name: Install Neovim 0.11.3
  ansible.builtin.apt:
    deb: /tmp/nvim.deb
  become: yes
