- name: Install Neovim — set local vars
  ansible.builtin.set_fact:
    nvim_version: "v0.11.3"
    nvim_arch: "{{ (ansible_architecture == 'aarch64') | ternary('linux-arm64','linux-x86_64') }}"
    nvim_root: "/opt"
    nvim_dir: "/opt/nvim-0.11.3"
    nvim_symlink: "/usr/local/bin/nvim"
    nvim_tar: "/tmp/nvim-{{ (ansible_architecture == 'aarch64') | ternary('linux-arm64','linux-x86_64') }}.tar.gz"

- name: Download Neovim {{ nvim_version }} tarball
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim-{{ nvim_arch }}.tar.gz"
    dest: "{{ nvim_tar }}"
    mode: "0644"

- block:
    - name: Ensure target dir exists and is owned by root
      ansible.builtin.file:
        path: "{{ nvim_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install Neovim into {{ nvim_dir }}
      ansible.builtin.unarchive:
        src: "{{ nvim_tar }}"
        dest: "{{ nvim_dir }}"
        remote_src: yes
        extra_opts: ["--strip-components=1"]
      args:
        creates: "{{ nvim_dir }}/bin/nvim" # idempotent

    - name: Symlink nvim into PATH
      ansible.builtin.file:
        src: "{{ nvim_dir }}/bin/nvim"
        dest: "{{ nvim_symlink }}"
        state: link
        force: yes

    - name: Stable /opt/nvim -> {{ nvim_dir }} symlink
      ansible.builtin.file:
        src: "{{ nvim_dir }}"
        dest: "{{ nvim_root }}/nvim"
        state: link
        force: yes
  become: yes
