---
- name: Add Neovim stable PPA
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
    update_cache: yes
  become: yes

- name: Install Neovim
  ansible.builtin.apt:
    name: neovim
    state: present
  become: yes
