---
- name: Mina's local machine bootstrap
  hosts: localhost
  connection: local
  gather_facts: yes

  # IMPORTANT: don't become at the play level so $HOME stays your user.
  become: false

  vars:
    # Resolve your actual user/home even if some tasks escalate later.
    target_user: "{{ lookup('env','USER') }}"
    target_home: "{{ lookup('env','HOME') }}"

    # Tooling versions/paths
    tpm_dir: "{{ target_home }}/.tmux/plugins/tpm"
    nvm_version: "v0.39.7"
    node_lts: "lts/*"

  pre_tasks:
    - name: Show who/where we are installing to
      ansible.builtin.debug:
        msg:
          - "user: {{ target_user }}"
          - "home: {{ target_home }}"

  tasks:
    # Common base (inside this file, use become: yes only where needed)
    - name: Common base
      ansible.builtin.include_tasks: "tasks/common.yml"

    # Language/tool modules (auto-include everything in langs/)
    - name: Include all language setup files from langs/
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ lookup('fileglob', playbook_dir + '/langs/*.yml', wantlist=True) | sort }}"
      loop_control:
        label: "{{ item | basename }}"

    # Neovim (split out if you want)
    - name: Install Neovim and friends
      ansible.builtin.include_tasks: "tasks/neovim.yml"
